<script setup>
import { computed, onMounted, ref } from 'vue';
import { CheckCircle2, FileText, LoaderCircle, MapPinned, Search, ShieldAlert, Trash2, X } from 'lucide-vue-next';
import { useAlonaAuthStore } from '../../stores/alonaAuthStore';

const store = useAlonaAuthStore();
const pendingUsers = ref([]); const approvedRiders = ref([]); const search = ref(''); const documentUser = ref(null); const rejectionUser = ref(null); const rejectionReason = ref(''); const assignmentUser = ref(null); const locations = ref([]); const selectedRegion = ref(null); const selectedProvince = ref(null); const selectedCities = ref([]); const busy = ref(false); const notice = ref('');
const filteredPending = computed(() => pendingUsers.value.filter((user) => `${user.first_name} ${user.last_name} ${user.email}`.toLowerCase().includes(search.value.toLowerCase())));
const locationLabel = (location) => location.city_municipality_name || location.province_name || location.region_name;
const refresh = async () => { [pendingUsers.value, approvedRiders.value] = await Promise.all([store.fetchUsersByStatus('PENDING'), store.fetchUsersByStatus('APPROVED')]); };
const review = async (user, action) => { busy.value = true; try { await store.reviewUser(user.id, action, rejectionReason.value); rejectionUser.value = null; rejectionReason.value = ''; notice.value = `Application ${action.toLowerCase()}d.`; await refresh(); } catch (error) { notice.value = error.message; } finally { busy.value = false; } };
const openAssignment = async (user) => { assignmentUser.value = user; locations.value = [...(user.locations || [])]; selectedRegion.value = null; selectedProvince.value = null; selectedCities.value = []; if (!store.regions.length) await store.loadRegions(); };
const chooseRegion = async (region) => { selectedRegion.value = region; selectedProvince.value = null; selectedCities.value = []; await store.loadProvinces(region); };
const chooseProvince = async (province) => { selectedProvince.value = province; selectedCities.value = []; await store.loadMunicipalities(province); };
const toggleCity = (city) => { selectedCities.value = selectedCities.value.some((item) => item.code === city.code) ? selectedCities.value.filter((item) => item.code !== city.code) : [...selectedCities.value, city]; };
const selectAllCities = () => { selectedCities.value = selectedCities.value.length === store.municipalities.length ? [] : [...store.municipalities]; };
const addProvince = () => { if (!selectedRegion.value || !selectedProvince.value) return; const item = { region_name: selectedRegion.value.name, province_name: selectedProvince.value.name, city_municipality_name: null, psgc_code: selectedProvince.value.code }; if (!locations.value.some((location) => location.psgc_code === item.psgc_code)) locations.value.push(item); };
const addCities = () => { if (!selectedRegion.value || !selectedProvince.value) return; const items = selectedCities.value.map((city) => ({ region_name: selectedRegion.value.name, province_name: selectedProvince.value.name, city_municipality_name: city.name, psgc_code: city.code })); locations.value = [...locations.value, ...items.filter((item) => !locations.value.some((existing) => existing.psgc_code === item.psgc_code))]; selectedCities.value = []; };
const saveLocations = async () => { busy.value = true; try { await store.saveAssignedLocations(assignmentUser.value.id, locations.value); assignmentUser.value.locations = [...locations.value]; notice.value = 'Rider coverage saved.'; assignmentUser.value = null; } catch (error) { notice.value = error.message; } finally { busy.value = false; } };
const removeLocation = (location) => { locations.value = locations.value.filter((item) => item.psgc_code !== location.psgc_code); };
onMounted(refresh);
</script>
<template>
  <section class="border border-slate-200 bg-white shadow-sm"><header class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 p-5"><div><p class="text-xs font-black uppercase tracking-widest text-teal-700">Access administration</p><h2 class="mt-1 text-xl font-black">Rider & staff approval queue</h2></div><label class="relative w-full sm:w-64"><Search class="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input v-model="search" class="w-full border border-slate-300 py-2 pl-9 pr-3 text-sm" placeholder="Search applicant" /></label></header><div v-if="notice" class="border-b border-teal-100 bg-teal-50 px-5 py-3 text-sm font-bold text-teal-800">{{ notice }}</div><div class="p-5"><h3 class="text-xs font-black uppercase tracking-widest text-slate-500">Pending applications ({{ filteredPending.length }})</h3><div class="mt-3 grid gap-3 lg:grid-cols-2"><article v-for="user in filteredPending" :key="user.id" class="border border-slate-200 p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-black">{{ user.first_name }} {{ user.last_name }}</p><p class="mt-1 text-xs text-slate-500">{{ user.email }} · {{ user.role }}</p></div><span class="bg-amber-100 px-2 py-1 text-[10px] font-black text-amber-800">PENDING</span></div><p class="mt-3 text-xs text-slate-600">{{ user.province }}, {{ user.municipality }}, {{ user.barangay }}</p><div class="mt-4 flex flex-wrap gap-2"><button class="inline-flex items-center gap-1 text-xs font-bold text-teal-700" @click="documentUser = user"><FileText class="h-4 w-4" />View documents</button><button class="inline-flex items-center gap-1 bg-emerald-700 px-3 py-2 text-xs font-bold text-white" :disabled="busy" @click="review(user, 'APPROVE')"><CheckCircle2 class="h-4 w-4" />Approve</button><button class="inline-flex items-center gap-1 bg-rose-700 px-3 py-2 text-xs font-bold text-white" @click="rejectionUser = user"><ShieldAlert class="h-4 w-4" />Reject</button></div></article></div><p v-if="!filteredPending.length" class="border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No pending applications.</p><h3 class="mt-8 text-xs font-black uppercase tracking-widest text-slate-500">Approved riders ({{ approvedRiders.length }})</h3><div class="mt-3 divide-y divide-slate-100 border border-slate-200"><div v-for="user in approvedRiders.filter((item) => item.role === 'RIDER')" :key="user.id" class="flex flex-wrap items-center justify-between gap-3 p-4"><div><p class="font-bold">{{ user.first_name }} {{ user.last_name }}</p><p class="text-xs text-slate-500">{{ (user.locations || []).map(locationLabel).join(' · ') || 'No delivery locations assigned' }}</p></div><button class="inline-flex items-center gap-1 bg-slate-950 px-3 py-2 text-xs font-bold text-white" @click="openAssignment(user)"><MapPinned class="h-4 w-4" />Assign delivery locations</button></div></div></div>
    <div v-if="documentUser" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" @click.self="documentUser = null"><article class="w-full max-w-xl bg-white p-6 shadow-2xl"><div class="flex justify-between"><h3 class="text-xl font-black">{{ documentUser.first_name }} {{ documentUser.last_name }} documents</h3><button @click="documentUser = null"><X class="h-5 w-5" /></button></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><a v-for="(url, type) in documentUser.document_urls" :key="type" :href="url" target="_blank" rel="noreferrer" class="border border-slate-200 p-4 text-sm font-bold text-teal-700">{{ type.replaceAll('_', ' ') }}<span class="mt-2 block text-xs">Open document</span></a></div></article></div>
    <div v-if="rejectionUser" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><form class="w-full max-w-md bg-white p-6" @submit.prevent="review(rejectionUser, 'REJECT')"><div class="flex justify-between"><h3 class="text-xl font-black">Reject application</h3><button type="button" @click="rejectionUser = null"><X class="h-5 w-5" /></button></div><textarea v-model="rejectionReason" required rows="4" class="mt-5 w-full border border-slate-300 p-3 text-sm" placeholder="Required feedback reason" /><button class="mt-4 w-full bg-rose-700 px-4 py-3 text-sm font-black text-white">Reject application</button></form></div>
    <div v-if="assignmentUser" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><article class="flex max-h-[90vh] w-full max-w-4xl flex-col bg-white"><header class="flex justify-between border-b border-slate-200 p-5"><div><h3 class="text-xl font-black">Assign locations to {{ assignmentUser.first_name }} {{ assignmentUser.last_name }}</h3><p class="mt-1 text-sm text-slate-500">Select a province or multiple cities.</p></div><button @click="assignmentUser = null"><X class="h-5 w-5" /></button></header><div class="grid flex-1 gap-5 overflow-y-auto p-5 lg:grid-cols-2"><div><select class="field" @change="chooseRegion(store.regions.find((item) => item.code === $event.target.value))"><option value="">Region</option><option v-for="region in store.regions" :key="region.code" :value="region.code">{{ region.name }}</option></select><select class="field" :disabled="!selectedRegion" @change="chooseProvince(store.provinces.find((item) => item.code === $event.target.value))"><option value="">Province</option><option v-for="province in store.provinces" :key="province.code" :value="province.code">{{ province.name }}</option></select><div class="mt-3 flex gap-2"><button class="flex-1 bg-slate-100 p-2 text-xs font-black" :disabled="!selectedProvince" @click="addProvince">Add entire province</button><button class="flex-1 bg-teal-700 p-2 text-xs font-black text-white" :disabled="!store.municipalities.length" @click="addCities">Add selected cities</button></div><div class="mt-4 border border-slate-200"><div class="flex justify-between bg-slate-50 p-3 text-xs font-black"><span>Cities / municipalities</span><button class="text-teal-700" @click="selectAllCities">Select all</button></div><label v-for="city in store.municipalities" :key="city.code" class="flex gap-3 border-b border-slate-100 p-3 text-sm"><input type="checkbox" :checked="selectedCities.some((item) => item.code === city.code)" @change="toggleCity(city)" />{{ city.name }}</label></div></div><div><p class="text-xs font-black uppercase tracking-widest text-slate-500">Active coverage</p><div class="mt-3 space-y-2"><div v-for="location in locations" :key="location.psgc_code" class="flex justify-between border border-slate-200 p-3 text-sm"><span>{{ locationLabel(location) }}</span><button class="text-rose-700" @click="removeLocation(location)"><Trash2 class="h-4 w-4" /></button></div></div></div></div><footer class="flex justify-end gap-3 border-t border-slate-200 p-4"><button class="px-4 py-2 text-sm font-bold" @click="assignmentUser = null">Cancel</button><button class="bg-slate-950 px-4 py-2 text-sm font-black text-white" :disabled="busy" @click="saveLocations"><LoaderCircle v-if="busy" class="inline h-4 w-4 animate-spin" /> Save locations</button></footer></article></div>
  </section>
</template>
<style scoped>.field{margin-top:.75rem;width:100%;border:1px solid #cbd5e1;background:white;padding:.7rem;font-size:.875rem}</style>
