<script setup>
import { computed, onMounted, ref } from 'vue';
import { Check, FileCheck2, LoaderCircle, Search, ShieldCheck, Truck, X } from 'lucide-vue-next';
import { useAlonaLogisticsStore } from '../../stores/alonaLogisticsStore';
import { philippineAddressService } from '../../services/philippineAddressService';

const store = useAlonaLogisticsStore();
const search = ref('');
const applicationFilter = ref('all');
const selectedRider = ref(null);
const assignmentRider = ref(null);
const rejectionReason = ref('');
const provinces = ref([]);
const cities = ref([]);
const selectedProvince = ref('');
const selectedCity = ref('');
const busy = ref(null);
const notice = ref('');

const filteredRiders = computed(() => store.riders.filter((rider) => {
  const term = search.value.toLowerCase();
  const matchesSearch = !term || [rider.full_name, rider.phone, rider.license_number, rider.agency?.name, rider.courier_type]
    .filter(Boolean).join(' ').toLowerCase().includes(term);
  const matchesApplication = applicationFilter.value === 'all' || rider.application_status === applicationFilter.value;
  return matchesSearch && matchesApplication;
}));
const riderZones = computed(() => assignmentRider.value ? store.zones.filter((zone) => (assignmentRider.value.zones || []).some((item) => String(item.id) === String(zone.id))) : []);
const availableZones = computed(() => store.zones.filter((zone) => {
  const provinceMatch = !selectedProvince.value || zone.province === selectedProvince.value;
  const cityMatch = !selectedCity.value || zone.city_municipality === selectedCity.value;
  return provinceMatch && cityMatch;
}));
const citiesForProvince = computed(() => cities.value);

const courierLabel = (rider) => ({ LBC: 'LBC', JNT_EXPRESS: 'J&T Express', FLASH_EXPRESS: 'Flash Express', IN_HOUSE: 'In-House', internal: 'In-House' }[rider.courier_type || rider.rider_kind] || rider.courier_type || rider.rider_kind || 'In-House');
const statusLabel = (status) => String(status || 'active').replaceAll('_', ' ');
const isPending = (rider) => rider.application_status === 'pending_review' || !rider.application_status;

const run = async (key, action) => { busy.value = key; notice.value = ''; try { await action(); notice.value = 'Rider record updated.'; } catch (error) { notice.value = error.message || 'Unable to update rider.'; } finally { busy.value = null; } };
const approve = (rider) => run(`approve-${rider.id}`, async () => { await store.reviewRider(rider.id, 'approve'); });
const reject = (rider) => run(`reject-${rider.id}`, async () => { if (!rejectionReason.value.trim()) throw new Error('Enter a rejection reason.'); await store.reviewRider(rider.id, 'reject', rejectionReason.value); rejectionReason.value = ''; selectedRider.value = null; });
const setAccountStatus = (rider, status) => run(`status-${rider.id}`, async () => { await store.updateRiderStatus(rider.id, status); });
const verifyDocument = (document, status) => run(`document-${document.id}`, async () => { await store.verifyRiderDocument(selectedRider.value.id, document.id, status); });
const openAssignment = async (rider) => { assignmentRider.value = rider; selectedProvince.value = ''; selectedCity.value = ''; cities.value = []; };
const loadCities = async () => { selectedCity.value = ''; const province = provinces.value.find((item) => item.name === selectedProvince.value); cities.value = province ? await philippineAddressService.getCities(province) : []; };
const assignZone = (zone, event) => run(`zone-${zone.id}`, async () => { const riderId = event.target.value; await store.assignZoneRider(zone.id, riderId || null); if (assignmentRider.value) assignmentRider.value = store.riders.find((item) => String(item.id) === String(assignmentRider.value.id)); });

onMounted(async () => { provinces.value = await philippineAddressService.getProvinces(); });
</script>

<template>
  <section class="overflow-hidden border border-slate-200 bg-white shadow-sm">
    <header class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 px-5 py-4"><div><p class="text-[11px] font-black uppercase tracking-[0.2em] text-teal-700">Fleet administration</p><h2 class="mt-1 text-xl font-black">Rider applications & directory</h2><p class="mt-1 text-sm text-slate-500">Review credentials, assign Philippine delivery areas, and control account access.</p></div><label class="relative block w-full sm:w-64"><Search class="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input v-model="search" class="w-full border border-slate-300 py-2 pl-9 pr-3 text-sm outline-none focus:border-teal-600" placeholder="Search rider or agency" /></label></header>
    <div class="flex flex-wrap items-center gap-2 border-b border-slate-200 px-5 py-3"><button v-for="filter in [{ value: 'all', label: 'All riders' }, { value: 'pending_review', label: 'Pending applications' }, { value: 'approved', label: 'Approved' }, { value: 'rejected', label: 'Rejected' }]" :key="filter.value" class="px-3 py-2 text-xs font-black" :class="applicationFilter === filter.value ? 'bg-teal-700 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'" @click="applicationFilter = filter.value">{{ filter.label }}</button><span v-if="notice" class="ml-auto text-xs font-bold text-teal-700">{{ notice }}</span></div>
    <div class="overflow-x-auto"><table class="w-full min-w-[1100px] text-left text-sm"><thead class="bg-slate-50 text-[11px] font-black uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Rider</th><th class="px-5 py-3">Courier type</th><th class="px-5 py-3">Philippine coverage</th><th class="px-5 py-3">Documents</th><th class="px-5 py-3">Application</th><th class="px-5 py-3">Account</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="rider in filteredRiders" :key="rider.id" class="hover:bg-teal-50/30"><td class="px-5 py-4"><p class="font-bold">{{ rider.full_name }}</p><p class="mt-1 text-xs text-slate-500">{{ rider.phone || rider.email || 'No contact details' }}</p></td><td class="px-5 py-4"><span class="inline-flex items-center gap-1.5 bg-slate-100 px-2.5 py-1 text-[11px] font-black text-slate-700"><Truck class="h-3.5 w-3.5" />{{ courierLabel(rider) }}</span></td><td class="px-5 py-4"><p class="font-semibold">{{ rider.zones?.[0]?.city_municipality || rider.zones?.[0]?.name || 'Unassigned' }}</p><p class="mt-1 text-xs text-slate-500">{{ rider.zones?.[0]?.province || '' }}</p></td><td class="px-5 py-4"><button class="inline-flex items-center gap-1.5 text-xs font-bold text-teal-700" @click="selectedRider = rider"><FileCheck2 class="h-4 w-4" />{{ rider.documents?.length || 0 }} files</button></td><td class="px-5 py-4"><span class="px-2 py-1 text-[10px] font-black uppercase" :class="isPending(rider) ? 'bg-amber-100 text-amber-800' : rider.application_status === 'approved' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'">{{ statusLabel(rider.application_status || 'pending_review') }}</span></td><td class="px-5 py-4"><span class="text-xs font-black uppercase" :class="rider.status === 'suspended' || rider.status === 'inactive' ? 'text-rose-700' : 'text-emerald-700'">{{ statusLabel(rider.status) }}</span></td><td class="px-5 py-4 text-right"><div class="flex justify-end gap-2"><button v-if="isPending(rider)" class="px-2 py-1 text-xs font-bold text-emerald-700 hover:bg-emerald-50" :disabled="busy === `approve-${rider.id}`" @click="approve(rider)"><Check class="inline h-3.5 w-3.5" /> Approve</button><button v-if="isPending(rider)" class="px-2 py-1 text-xs font-bold text-rose-700 hover:bg-rose-50" @click="selectedRider = rider">Reject</button><button class="px-2 py-1 text-xs font-bold text-teal-700 hover:bg-teal-50" @click="openAssignment(rider)">Assign area</button><select class="border border-slate-300 px-2 py-1 text-xs font-bold" :value="rider.status" @change="setAccountStatus(rider, $event.target.value)"><option value="active">Activate</option><option value="on_duty">On duty</option><option value="suspended">Suspend</option><option value="inactive">Deactivate</option></select></div></td></tr><tr v-if="!filteredRiders.length"><td colspan="7" class="p-12 text-center text-sm text-slate-500">No riders match this filter.</td></tr></tbody></table></div>
+
+    <div v-if="selectedRider" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" @click.self="selectedRider = null"><article class="w-full max-w-xl border border-slate-200 bg-white p-6 shadow-2xl"><div class="flex items-start justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-teal-700">Credential review</p><h3 class="mt-1 text-xl font-black">{{ selectedRider.full_name }}</h3></div><button aria-label="Close" @click="selectedRider = null"><X class="h-5 w-5" /></button></div><div class="mt-5 space-y-3"><div v-for="document in selectedRider.documents || []" :key="document.id" class="flex flex-wrap items-center justify-between gap-3 border border-slate-200 p-4"><div><p class="font-bold">{{ document.document_type }}</p><p class="mt-1 text-xs text-slate-500">{{ document.status }}{{ document.expires_at ? ` · Expires ${document.expires_at}` : '' }}</p></div><div class="flex items-center gap-3"><a :href="document.file_url || document.file_path" target="_blank" rel="noreferrer" class="text-xs font-bold text-teal-700">View</a><button class="text-xs font-bold text-emerald-700" @click="verifyDocument(document, 'verified')">Verify</button><button class="text-xs font-bold text-rose-700" @click="verifyDocument(document, 'rejected')">Reject</button></div></div><p v-if="!selectedRider.documents?.length" class="border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No documents uploaded.</p></div><div v-if="isPending(selectedRider)" class="mt-6 border-t border-slate-200 pt-5"><label class="block text-xs font-black uppercase tracking-wider text-slate-500">Rejection reason<textarea v-model="rejectionReason" rows="2" class="mt-2 w-full border border-slate-300 p-3 text-sm" placeholder="Required when rejecting an application" /></label><div class="mt-3 flex justify-end gap-2"><button class="px-3 py-2 text-sm font-bold text-slate-600" @click="selectedRider = null">Cancel</button><button class="bg-rose-700 px-3 py-2 text-sm font-bold text-white" @click="reject(selectedRider)">Reject application</button></div></div></article></div>
+
+    <div v-if="assignmentRider" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" @click.self="assignmentRider = null"><article class="w-full max-w-2xl border border-slate-200 bg-white p-6 shadow-2xl"><div class="flex items-start justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-teal-700">Territory assignment</p><h3 class="mt-1 text-xl font-black">{{ assignmentRider.full_name }}</h3><p class="mt-1 text-sm text-slate-500">Filter by Philippine province and city/municipality.</p></div><button aria-label="Close" @click="assignmentRider = null"><X class="h-5 w-5" /></button></div><div class="mt-5 grid gap-3 sm:grid-cols-2"><select v-model="selectedProvince" class="border border-slate-300 px-3 py-2 text-sm" @change="loadCities"><option value="">All provinces</option><option v-for="province in provinces" :key="province.code" :value="province.name">{{ province.name }}</option></select><select v-model="selectedCity" class="border border-slate-300 px-3 py-2 text-sm" :disabled="!selectedProvince"><option value="">All cities / municipalities</option><option v-for="city in citiesForProvince" :key="city.code" :value="city.name">{{ city.name }}</option></select></div><div class="mt-5 max-h-72 space-y-2 overflow-y-auto"><label v-for="zone in availableZones" :key="zone.id" class="flex items-center justify-between border border-slate-200 p-3"><span><span class="block font-bold">{{ zone.name }}</span><span class="text-xs text-slate-500">{{ zone.city_municipality || 'City/municipality not set' }}, {{ zone.province || 'Province not set' }}</span></span><select class="border border-slate-300 px-2 py-1 text-xs font-bold" :value="zone.default_rider_id === assignmentRider.id ? assignmentRider.id : ''" @change="assignZone(zone, $event)"><option value="">Unassigned</option><option :value="assignmentRider.id">Assign this rider</option></select></label><p v-if="!availableZones.length" class="p-8 text-center text-sm text-slate-500">No city/province zones match the filter.</p></div></article></div>
+  </section>
+</template>
