<script setup>
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useHubStore } from '../../stores/hub';

const route = useRoute(); const router = useRouter(); const store = useHubStore(); const selected = ref([]); const filters = reactive({ search: '', date_scanned: '', page: 1, per_page: 15 }); let timer;
const load = () => store.fetchInventory(route.params.id, { ...filters });
const search = () => { clearTimeout(timer); timer = setTimeout(() => { filters.page = 1; load(); }, 300); };
const toggleAll = (event) => { selected.value = event.target.checked ? store.inventory.data.map((order) => order.id) : []; };
onMounted(load);
</script>

<template>
  <main class="min-h-screen bg-[#f4f7f6] text-slate-900"><header class="border-b border-slate-200 bg-white"><div class="mx-auto max-w-7xl px-6 py-6"><button class="text-sm font-bold text-teal-700" @click="router.push('/hubs')">&larr; Hub capacity</button><div class="mt-3 flex flex-wrap items-center justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-widest text-teal-700">Inventory audit</p><h1 class="text-3xl font-black">Packages in hub #{{ route.params.id }}</h1></div><button :disabled="!selected.length" class="bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-40" @click="router.push({ path: '/transfers', query: { from_hub_id: route.params.id, order_ids: selected.join(',') } })">Request inter-hub transfer ({{ selected.length }})</button></div></div></header><div class="mx-auto max-w-7xl px-6 py-8"><section class="border border-slate-200 bg-white shadow-sm"><div class="flex flex-wrap gap-3 border-b border-slate-200 p-5"><input v-model="filters.search" @input="search" placeholder="Search AWB, sender, recipient" class="border px-3 py-2 text-sm" /><input v-model="filters.date_scanned" type="date" @change="filters.page = 1; load()" class="border px-3 py-2 text-sm" /></div><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="w-12 px-5 py-3"><input type="checkbox" @change="toggleAll" /></th><th class="px-5 py-3">AWB</th><th class="px-5 py-3">Route plan</th><th class="px-5 py-3">Arrival</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="order in store.inventory.data" :key="order.id"><td class="px-5 py-4"><input v-model="selected" type="checkbox" :value="order.id" /></td><td class="px-5 py-4 font-mono font-bold">{{ order.awb_number }}</td><td class="px-5 py-4 text-slate-600">{{ order.route_plan?.route_path_json?.map((step) => step.name).join(' → ') || 'Not planned' }}</td><td class="px-5 py-4 text-slate-500">{{ order.hub_scanned_at ? new Date(order.hub_scanned_at).toLocaleString() : '—' }}</td><td class="px-5 py-4"><span class="bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800">{{ order.status }}</span></td></tr><tr v-if="!store.inventory.data.length"><td colspan="5" class="p-10 text-center text-slate-400">No packages currently in this hub.</td></tr></tbody></table></div><footer class="flex justify-between border-t p-4 text-sm text-slate-500"><span>{{ store.inventory.total }} packages</span><div class="flex gap-2"><button :disabled="filters.page <= 1" class="border px-3 py-1 disabled:opacity-40" @click="filters.page--; load()">Previous</button><button :disabled="filters.page >= store.inventory.last_page" class="border px-3 py-1 disabled:opacity-40" @click="filters.page++; load()">Next</button></div></footer></section></div></main>
</template>