[program:horizon]
command=php /var/www/html/artisan horizon
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
stopwaitsecs=3600
redirect_stderr=true
stdout_logfile=/var/log/horizon.log
